services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=php_db"
      - "DB_USER=user"
      - "DB_PASSWORD=secret"
      - "XDG_CONFIG_HOME=/app"
    ports:
      - "80:80"
    networks:
      - php_network
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=php_db"
      - "DB_USER=user"
      - "DB_PASSWORD=secret"
    networks:
      - php_network
    extra_hosts:
      - host.docker.internal:host-gateway
  mysql:
    image: mysql
    volumes:
      - database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=php_db"
    ports:
      - "3306:3306"
    networks:
      - php_network
volumes:
  database:
networks:
  php_network:
    name: php_network
    ipam:
      config:
        - subnet: 172.28.0.0/16