services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    env_file:
      - .env
    environment:
      - "XDG_CONFIG_HOME=/app"
    ports:
      - "80:80"
    networks:
      - php_network
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    env_file:
      - .env
    networks:
      - php_network
    extra_hosts:
      - host.docker.internal:host-gateway
  mysql:
    image: mysql
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - php_network
volumes:
  database:
networks:
  php_network:
    name: php_network
    ipam:
      config:
        - subnet: 172.28.0.0/16